# Generated by Django 4.2.5 on 2023-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadsTails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=100)),
                ('date_res', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
